# container-based env for caching
sudo: false
cache:
  directries:
  - $HOME/.stack

# additional libraries
addons:
  apt:
    packages:
    - libgmp-dev

# get stack binary
before_install:
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$HOME/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# install GHC
install:
- stack --no-terminal setup

# build project
script:
- stack --no-terminal build
